spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.20.21:3306/train?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false
    username: wxy
    password:
logging:
  level:
    root: info
value:
  redis-address: "101.42.20.21"
  redis-port: 6379
  redis-user:
  redis-auth: "123456"

server:
  port: 8020

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true

custom:
  CARRIAGE_LENGTH: 120
  YINGZUO: 0,
  YINGWO: 1,
  RUANWO: 2,
  YIDENG: 3,
  ERDENG: 4,
  SHANGWU: 5,

jwt:
  secret: "fjoewjfowejoifwefweopfkweo"
  expiration: 3600000

alipay:
  appId: 9021000125632298
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCHKwCzHbeAB5dTETwNiJ+kFJABrHtmzgY5EsNLPmbAFKsQV2NmUnjiahzTklfTYCK2K+wwna8tJZFWd0/64idvQ8Rm7umptXiOOHn1xCBuQXX3PaDmUGJ0m5tbWvSrlPdX9o3bNjiyRsbZvjqAZWPl6HVKx86XBAOZHUecNCBLAHxDLxSY1QJz4HaK3Rp4draPBKoOfPjix1H4nxBIDSjlyiO7xPdPzCrh92OxDwuBmJSWeFiCedCDUoeyY87M/GZriD9haU/y+EquaBulP6pXsnmtkLskfrz0ytA+sLjVaHw9BZ28rQG8HjWFgdmsNyadE7ik9J4F7Zbb+PMZpg0jAgMBAAECggEAOlF/d8h2h7K+w4RIGL69whltGIvGolB5tt41jJ1bz7wbIm3R4S/sICQQU+hsJDLyRw8kVMVz81KmJlxMEb7JrOPcNV0XS7WUUihj1nnMVEXCE+5vIW/FSvJoUT4pGm6nWThzdAUs6R5IZWIB86vLMkLdeGpE5DtDIijT4L1MwY7Pht2NotfTSayndGPgTaivjBY8/AoXi5ybeTncRESUdAEEgfidbVdrco6sM3KrRUYVnltHEcZJ/OQuan7WxJzA2p1ORpQ3p7Mu+jmr8F8SHOIbxVcjTK0jjWhBQW6Gg1qTkfDbWuwMvi2csqJD1MJDIdNxUlz/77q6YGk98Z0HIQKBgQC8Mb1iEk0nvAXTzHbPsCegyZNGi/73gJdXWIACJ3udPH1PuVvdXp8M8Qm/NerXqbteGHEyaTDu0u+As4mxMzsKxztGGr3H3yOnPVjltU5CVMb8wm9JUXmvMHPeZKy8vPrm3d0qhvrE/RKZzg2jU49L4YeKbvIZedXaC/tY6HZxLQKBgQC33lXz2lFVEsC7brvcUICm1uHTLKwcM/n0j6G0FCzvbUeJRZ1KtIuqb3FB0Eq1x/1q4//t4mhRYb7fmy2v6Xe4gFs78qqIldCYKotDB0YpbujNWxRURmUg8AQZIQi6thiPyj2D3tK5hWgleWRKtSonsAIQ+DT62m/Kw0hmanNJjwKBgQCUz4f/OpWD6+t3tN/mDlbnjz1DtYOhVi9VxAdErM/UX3Z/SgTYIPAHnbmlVw8iBXbBSvaHdCJbVrRHwrAITIhNV4kJQC/9EfbxUVMwIJOHY94NE/pHsYNVAi09F8J3Y7/KOnmeHSnCBpNkx0iFc5eF2woAbwZFGs/9IShY/0hY6QKBgBO9bwTrH2g+xypYTRruGaHP2BbP6PpuKhuzf+zRbbGWzeNS8fwfPg9iP4qNTjgN7IsZR1TGxeRW1iMzicglDJFmVmUtPFnFm8t6ZdEgasvv+FZzvM7/b8QFgKsh/Mnu2tw1Hj2WIpGAXRoI2lea85enMdGYlDeKVA40wQUd0JrJAoGAdVvTBaWkwuBVVF20/B84NWhGgMZ4JbbP80J4CwbskqZNRcXATWOgcOEnFY1kO0bCjRAW9NQ7j+F+6pBWh2hiM/wDpeR3mRld2ujKH9H9+lA7NPLzIXoSaUZVgfKbSv1sO+8IARYdVK2h1vi6mT+8YmjGl0BxEEiuSKJ8bR0mWpI=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtFuL7PKmlTTZfr5/T3NK6fedeFGz6oa91P3PVcaP5k6tMP2upkNo82sR4gJwdPc7aKiyCfP5pyo6om17CH13Yw2dy6xMIrYI1N6+CzZsDu1a7ICdfsBmhJzBIgkkUyfpKsEOCNNGQBQanX3CO9IMre+uyT4qB2YvqDv93g3DEg1jeFOVla8KXGmxgGkQRWTmVmTPCy/zy+EZolx+ZcbFfSaOy1cnHm4yz5VWsTcsm7HWQ10Biz/gr3QvSPVGOkeno0YFXXnrBCcpRWrORIUihJMP0+QdUcLdgk7VZHIT1w7dK9q9laCcHRUy4sNUqF10Q796JO25oYLpMD78PNddjwIDAQAB
#  异步通知地址，还需在支付宝开放平台配置
  notifyUrl: "http://train-server.wxyww.top/payCallback"
# 同步回调地址，还需在支付宝开放平台配置
  returnUrl: "http://train-client.wxyww.top/#/order"
